AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 11:28:00.180095 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 11:28:00.180709 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 11:28:09.473994 2023] [authz_core:error] [pid 17] [client 172.22.0.1:40600] AH01630: client denied by server configuration: /var/www/html/web/web.config
[Mon Sep 11 11:28:09.475982 2023] [negotiation:error] [pid 17] [client 172.22.0.1:40600] AH00687: Negotiation: discovered file(s) matching request: /var/www/html/web/web (None could be negotiated).
[Mon Sep 11 11:28:14.606843 2023] [php7:notice] [pid 17] [client 172.22.0.1:40600] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:28:21.818476 2023] [php7:notice] [pid 20] [client 172.22.0.1:53164] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:29:18.398244 2023] [php7:notice] [pid 22] [client 172.22.0.1:50586] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:30:00.173939 2023] [php7:notice] [pid 21] [client 172.22.0.1:52174] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:32:17.597559 2023] [php7:notice] [pid 18] [client 172.22.0.1:56066] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:32:27.644228 2023] [php7:notice] [pid 17] [client 172.22.0.1:45066] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:34:17.248927 2023] [php7:notice] [pid 20] [client 172.22.0.1:36692] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:34:33.377658 2023] [php7:notice] [pid 18] [client 172.22.0.1:42814] Error: Class 'Drupal\\Component\\Utility\\Xss' not found in /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php on line 743 #0 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(378): Drupal\\Core\\Render\\Renderer->ensureMarkupIsSafe(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#2 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\\Core\\Render\\Renderer->render(Array)\n#3 /var/www/html/vendor/twig/twig/src/Environment.php(497) : eval()'d code(66): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#4 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_a559525fb1e43909b218d37f643940d0d5869be11be6b3d49c95757f7af682bb->doDisplay(Array, Array)\n#5 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array)\n#6 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\\Template->display(Array)\n#7 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\\Template->render(Array)\n#8 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/sev...', Array)\n#9 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\\Core\\Theme\\ThemeManager->render('form_element_la...', Array)\n#10 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#11 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\\Core\\Render\\Renderer->render(Array)\n#12 /var/www/html/vendor/twig/twig/src/Environment.php(497) : eval()'d code(75): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#13 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_8506fbf244e05bcf6a702c2b1e58311c08ca82e8ca556731607d3f72ab75740d->doDisplay(Array, Array)\n#14 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array)\n#15 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\\Template->display(Array)\n#16 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\\Template->render(Array)\n#17 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/sev...', Array)\n#18 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(487): Drupal\\Core\\Theme\\ThemeManager->render('form_element', Array)\n#19 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\\Core\\Render\\Renderer->doRender(Array)\n#20 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#21 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\\Core\\Render\\Renderer->render(Array)\n#22 /var/www/html/vendor/twig/twig/src/Environment.php(497) : eval()'d code(114): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#23 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_598de62d19839e35c04a8dd3dab010f180a577ad4dc916f19a9686325bd90cdc->doDisplay(Array, Array)\n#24 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array)\n#25 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\\Template->display(Array)\n#26 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\\Template->render(Array)\n#27 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/sev...', Array)\n#28 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\\Core\\Theme\\ThemeManager->render('install_page', Array)\n#29 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#30 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\\Core\\Render\\Renderer->render(Array)\n#31 /var/www/html/vendor/twig/twig/src/Environment.php(497) : eval()'d code(102): Drupal\\Core\\Template\\TwigExtension->escapeFilter(Object(Drupal\\Core\\Template\\TwigEnvironment), Array, 'html', NULL, true)\n#32 /var/www/html/vendor/twig/twig/src/Template.php(455): __TwigTemplate_58c9d97e6e58d926c7ef1e8a9d32f7d6cb23eac019e0acb887f3ce7a42e8b21c->doDisplay(Array, Array)\n#33 /var/www/html/vendor/twig/twig/src/Template.php(422): Twig\\Template->displayWithErrorHandling(Array, Array)\n#34 /var/www/html/vendor/twig/twig/src/Template.php(434): Twig\\Template->display(Array)\n#35 /var/www/html/web/core/themes/engines/twig/twig.engine(64): Twig\\Template->render(Array)\n#36 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('core/themes/sev...', Array)\n#37 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\\Core\\Theme\\ThemeManager->render('html', Array)\n#38 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, true)\n#39 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(144): Drupal\\Core\\Render\\Renderer->render(Array, true)\n#40 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\\Core\\Render\\Renderer->Drupal\\Core\\Render\\{closure}()\n#41 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(145): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#42 /var/www/html/web/core/lib/Drupal/Core/Render/BareHtmlPageRenderer.php(66): Drupal\\Core\\Render\\Renderer->renderRoot(Array)\n#43 /var/www/html/web/core/lib/Drupal/Core/ProxyClass/Render/BareHtmlPageRenderer.php(76): Drupal\\Core\\Render\\BareHtmlPageRenderer->renderBarePage(Array, 'Choose language', 'install_page', Array)\n#44 /var/www/html/web/core/includes/install.core.inc(1054): Drupal\\Core\\ProxyClass\\Render\\BareHtmlPageRenderer->renderBarePage(Array, 'Choose language', 'install_page', Array)\n#45 /var/www/html/web/core/includes/install.core.inc(160): install_display_output(Array, Array)\n#46 /var/www/html/web/core/install.php(44): install_drupal(Object(Composer\\Autoload\\ClassLoader))\n#47 {main}
[Mon Sep 11 11:35:00.938758 2023] [php7:notice] [pid 19] [client 172.22.0.1:42610] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 /var/www/html/web/core/lib/Drupal/Core/Config/BootstrapConfigStorageFactory.php(40): Drupal\\Core\\Database\\Database::getConnection()\n#3 /var/www/html/web/core/lib/Drupal/Core/Config/BootstrapConfigStorageFactory.php(31): Drupal\\Core\\Config\\BootstrapConfigStorageFactory::getDatabaseStorage()\n#4 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(1414): Drupal\\Core\\Config\\BootstrapConfigStorageFactory::get(Object(Composer\\Autoload\\ClassLoader))\n#5 /var/www/html/web/core/lib/Drupal/Core/Installer/InstallerKernel.php(48): Drupal\\Core\\DrupalKernel->getConfigStorage()\n#6 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(623): Drupal\\Core\\Installer\\InstallerKernel->getConfigStorage()\n#7 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(1345): Drupal\\Core\\DrupalKernel->discoverServiceProviders()\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(1254): Drupal\\Core\\DrupalKernel->initializeServiceProviders()\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(916): Drupal\\Core\\DrupalKernel->compileContainer()\n#10 /var/www/html/web/core/lib/Drupal/Core/Installer/InstallerKernel.php(20): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\Installer\\InstallerKernel->initializeContainer()\n#12 /var/www/html/web/core/includes/install.core.inc(430): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/core/includes/install.core.inc(115): install_begin_request(Object(Composer\\Autoload\\ClassLoader), Array)\n#14 /var/www/html/web/core/install.php(44): install_drupal(Object(Composer\\Autoload\\ClassLoader))\n#15 {main}
[Mon Sep 11 11:35:50.162223 2023] [php7:notice] [pid 21] [client 172.22.0.1:52134] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 /var/www/html/web/core/lib/Drupal/Core/Config/BootstrapConfigStorageFactory.php(40): Drupal\\Core\\Database\\Database::getConnection()\n#3 /var/www/html/web/core/lib/Drupal/Core/Config/BootstrapConfigStorageFactory.php(31): Drupal\\Core\\Config\\BootstrapConfigStorageFactory::getDatabaseStorage()\n#4 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(1414): Drupal\\Core\\Config\\BootstrapConfigStorageFactory::get(Object(Composer\\Autoload\\ClassLoader))\n#5 /var/www/html/web/core/lib/Drupal/Core/Installer/InstallerKernel.php(48): Drupal\\Core\\DrupalKernel->getConfigStorage()\n#6 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(623): Drupal\\Core\\Installer\\InstallerKernel->getConfigStorage()\n#7 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(1345): Drupal\\Core\\DrupalKernel->discoverServiceProviders()\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(1254): Drupal\\Core\\DrupalKernel->initializeServiceProviders()\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(916): Drupal\\Core\\DrupalKernel->compileContainer()\n#10 /var/www/html/web/core/lib/Drupal/Core/Installer/InstallerKernel.php(20): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\Installer\\InstallerKernel->initializeContainer()\n#12 /var/www/html/web/core/includes/install.core.inc(430): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/core/includes/install.core.inc(115): install_begin_request(Object(Composer\\Autoload\\ClassLoader), Array)\n#14 /var/www/html/web/core/install.php(44): install_drupal(Object(Composer\\Autoload\\ClassLoader))\n#15 {main}
[Mon Sep 11 11:37:10.071002 2023] [php7:notice] [pid 22] [client 172.22.0.1:54262] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:39:22.399861 2023] [php7:notice] [pid 20] [client 172.22.0.1:45764] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:43:14.930807 2023] [php7:notice] [pid 18] [client 172.22.0.1:42852] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:43:43.927480 2023] [php7:notice] [pid 19] [client 172.22.0.1:50766] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:44:23.466380 2023] [php7:notice] [pid 20] [client 172.22.0.1:34014] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:44:38.675800 2023] [php7:notice] [pid 22] [client 172.22.0.1:56618] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:45:00.294322 2023] [php7:notice] [pid 17] [client 172.22.0.1:57818] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:45:29.072188 2023] [php7:notice] [pid 20] [client 172.22.0.1:44690] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:45:33.571697 2023] [php7:notice] [pid 20] [client 172.22.0.1:44690] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:45:51.632168 2023] [php7:notice] [pid 18] [client 172.22.0.1:43450] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:46:09.290560 2023] [php7:notice] [pid 17] [client 172.22.0.1:35802] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:46:44.225304 2023] [php7:notice] [pid 20] [client 172.22.0.1:60264] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:51:55.454994 2023] [php7:notice] [pid 21] [client 172.22.0.1:57216] Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 404 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#2 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#3 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#8 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#12 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#13 {main}
[Mon Sep 11 11:52:13.567082 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.23.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 11:57:19.194156 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 11:57:19.196013 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 11:58:13.603817 2023] [php7:notice] [pid 16] [client 172.23.0.1:38200] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:00:13.510019 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 12:03:45.836051 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 12:03:45.836526 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 12:04:53.672911 2023] [php7:notice] [pid 17] [client 172.24.0.1:59192] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:07:47.041124 2023] [php7:notice] [pid 19] [client 172.24.0.1:35654] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:08:09.041763 2023] [php7:notice] [pid 21] [client 172.24.0.1:42352] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:08:13.571635 2023] [php7:notice] [pid 17] [client 172.24.0.1:42364] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:08:41.109337 2023] [php7:notice] [pid 19] [client 172.24.0.1:44556] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:09:30.529126 2023] [php7:notice] [pid 21] [client 172.24.0.1:39996] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:11:54.763650 2023] [php7:notice] [pid 17] [client 172.24.0.1:51734] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:14:14.361106 2023] [php7:notice] [pid 19] [client 172.24.0.1:53144] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:14:34.657334 2023] [php7:notice] [pid 21] [client 172.24.0.1:34678] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:15:16.892252 2023] [php7:notice] [pid 17] [client 172.24.0.1:35408] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:15:26.294090 2023] [php7:notice] [pid 22] [client 172.24.0.1:44102] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:16:04.791437 2023] [php7:notice] [pid 21] [client 172.24.0.1:46488] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:19:39.954610 2023] [php7:notice] [pid 20] [client 172.24.0.1:51052] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:23:58.224213 2023] [php7:notice] [pid 19] [client 172.24.0.1:47452] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:24:08.164746 2023] [php7:notice] [pid 18] [client 172.24.0.1:56824] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:24:24.532769 2023] [php7:notice] [pid 20] [client 172.24.0.1:46046] PDOException: SQLSTATE[HY000] [2002] Connection refused in /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/html/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(416): PDO->__construct('mysql:host=127....', 'root', 'test', Array)\n#1 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2 /var/www/html/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /var/www/html/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}
[Mon Sep 11 12:27:32.835290 2023] [php7:notice] [pid 19] [client 172.24.0.1:40968] Error: Class 'Drupal\\Component\\Utility\\Xss' not found in /var/www/html/web/core/modules/views/src/Plugin/views/field/EntityField.php on line 712 #0 /var/www/html/web/core/modules/views/src/Plugin/views/field/FieldPluginBase.php(1179): Drupal\\views\\Plugin\\views\\field\\EntityField->renderItems(Array)\n#1 /var/www/html/web/core/modules/views/views.theme.inc(238): Drupal\\views\\Plugin\\views\\field\\FieldPluginBase->advancedRender(Object(Drupal\\views\\ResultRow))\n#2 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(287): template_preprocess_views_view_field(Array, 'views_view_fiel...', Array)\n#3 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\\Core\\Theme\\ThemeManager->render('views_view_fiel...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#5 /var/www/html/web/core/modules/views/src/Plugin/views/field/FieldPluginBase.php(1746): Drupal\\Core\\Render\\Renderer->render(Array)\n#6 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(771): Drupal\\views\\Plugin\\views\\field\\FieldPluginBase->theme(Object(Drupal\\views\\ResultRow))\n#7 [internal function]: Drupal\\views\\Plugin\\views\\style\\StylePluginBase->elementPreRenderRow(Array)\n#8 /var/www/html/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(100): call_user_func_array(Array, Array)\n#9 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(781): Drupal\\Core\\Render\\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'silenced_deprec...', 'Drupal\\\\Core\\\\Ren...')\n#10 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(372): Drupal\\Core\\Render\\Renderer->doCallback('#pre_render', Array, Array)\n#11 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#12 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(710): Drupal\\Core\\Render\\Renderer->render(Array)\n#13 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(577): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->renderFields(Array)\n#14 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(468): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->renderGrouping(Array, Array, true)\n#15 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2170): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->render(Array)\n#16 /var/www/html/web/core/modules/views/src/ViewExecutable.php(1533): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->render()\n#17 /var/www/html/web/core/modules/views/src/Plugin/views/display/Page.php(183): Drupal\\views\\ViewExecutable->render()\n#18 /var/www/html/web/core/modules/views/src/ViewExecutable.php(1630): Drupal\\views\\Plugin\\views\\display\\Page->execute()\n#19 /var/www/html/web/core/modules/views/src/Element/View.php(77): Drupal\\views\\ViewExecutable->executeDisplay('page_1', Array)\n#20 [internal function]: Drupal\\views\\Element\\View::preRenderViewElement(Array)\n#21 /var/www/html/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(100): call_user_func_array(Array, Array)\n#22 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(781): Drupal\\Core\\Render\\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'silenced_deprec...', 'Drupal\\\\Core\\\\Ren...')\n#23 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(372): Drupal\\Core\\Render\\Renderer->doCallback('#pre_render', Array, Array)\n#24 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#25 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\\Core\\Render\\Renderer->render(Array, false)\n#26 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->Drupal\\Core\\Render\\MainContent\\{closure}()\n#27 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#28 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->prepare(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#29 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->renderResponse(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#30 [internal function]: Drupal\\Core\\EventSubscriber\\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#31 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#32 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent))\n#33 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#34 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#35 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#36 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#37 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#38 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#39 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#40 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#41 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#42 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#43 {main}
[Mon Sep 11 12:28:00.981443 2023] [php7:notice] [pid 21] [client 172.24.0.1:52660] Error: Class 'Drupal\\Component\\Utility\\Xss' not found in /var/www/html/web/core/modules/views/src/Plugin/views/field/EntityField.php on line 712 #0 /var/www/html/web/core/modules/views/src/Plugin/views/field/FieldPluginBase.php(1179): Drupal\\views\\Plugin\\views\\field\\EntityField->renderItems(Array)\n#1 /var/www/html/web/core/modules/views/views.theme.inc(238): Drupal\\views\\Plugin\\views\\field\\FieldPluginBase->advancedRender(Object(Drupal\\views\\ResultRow))\n#2 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(287): template_preprocess_views_view_field(Array, 'views_view_fiel...', Array)\n#3 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\\Core\\Theme\\ThemeManager->render('views_view_fiel...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#5 /var/www/html/web/core/modules/views/src/Plugin/views/field/FieldPluginBase.php(1746): Drupal\\Core\\Render\\Renderer->render(Array)\n#6 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(771): Drupal\\views\\Plugin\\views\\field\\FieldPluginBase->theme(Object(Drupal\\views\\ResultRow))\n#7 [internal function]: Drupal\\views\\Plugin\\views\\style\\StylePluginBase->elementPreRenderRow(Array)\n#8 /var/www/html/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(100): call_user_func_array(Array, Array)\n#9 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(781): Drupal\\Core\\Render\\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'silenced_deprec...', 'Drupal\\\\Core\\\\Ren...')\n#10 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(372): Drupal\\Core\\Render\\Renderer->doCallback('#pre_render', Array, Array)\n#11 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#12 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(710): Drupal\\Core\\Render\\Renderer->render(Array)\n#13 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(577): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->renderFields(Array)\n#14 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(468): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->renderGrouping(Array, Array, true)\n#15 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2170): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->render(Array)\n#16 /var/www/html/web/core/modules/views/src/ViewExecutable.php(1533): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->render()\n#17 /var/www/html/web/core/modules/views/src/Plugin/views/display/Page.php(183): Drupal\\views\\ViewExecutable->render()\n#18 /var/www/html/web/core/modules/views/src/ViewExecutable.php(1630): Drupal\\views\\Plugin\\views\\display\\Page->execute()\n#19 /var/www/html/web/core/modules/views/src/Element/View.php(77): Drupal\\views\\ViewExecutable->executeDisplay('page_1', Array)\n#20 [internal function]: Drupal\\views\\Element\\View::preRenderViewElement(Array)\n#21 /var/www/html/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(100): call_user_func_array(Array, Array)\n#22 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(781): Drupal\\Core\\Render\\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'silenced_deprec...', 'Drupal\\\\Core\\\\Ren...')\n#23 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(372): Drupal\\Core\\Render\\Renderer->doCallback('#pre_render', Array, Array)\n#24 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#25 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\\Core\\Render\\Renderer->render(Array, false)\n#26 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->Drupal\\Core\\Render\\MainContent\\{closure}()\n#27 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#28 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->prepare(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#29 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->renderResponse(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#30 [internal function]: Drupal\\Core\\EventSubscriber\\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#31 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#32 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent))\n#33 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#34 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#35 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#36 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#37 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#38 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#39 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#40 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#41 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#42 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#43 {main}
[Mon Sep 11 12:28:13.023398 2023] [php7:notice] [pid 17] [client 172.24.0.1:42196] Error: Class 'Drupal\\Component\\Utility\\Xss' not found in /var/www/html/web/core/modules/views/src/Plugin/views/field/EntityField.php on line 712 #0 /var/www/html/web/core/modules/views/src/Plugin/views/field/FieldPluginBase.php(1179): Drupal\\views\\Plugin\\views\\field\\EntityField->renderItems(Array)\n#1 /var/www/html/web/core/modules/views/views.theme.inc(238): Drupal\\views\\Plugin\\views\\field\\FieldPluginBase->advancedRender(Object(Drupal\\views\\ResultRow))\n#2 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(287): template_preprocess_views_view_field(Array, 'views_view_fiel...', Array)\n#3 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\\Core\\Theme\\ThemeManager->render('views_view_fiel...', Array)\n#4 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#5 /var/www/html/web/core/modules/views/src/Plugin/views/field/FieldPluginBase.php(1746): Drupal\\Core\\Render\\Renderer->render(Array)\n#6 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(771): Drupal\\views\\Plugin\\views\\field\\FieldPluginBase->theme(Object(Drupal\\views\\ResultRow))\n#7 [internal function]: Drupal\\views\\Plugin\\views\\style\\StylePluginBase->elementPreRenderRow(Array)\n#8 /var/www/html/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(100): call_user_func_array(Array, Array)\n#9 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(781): Drupal\\Core\\Render\\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'silenced_deprec...', 'Drupal\\\\Core\\\\Ren...')\n#10 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(372): Drupal\\Core\\Render\\Renderer->doCallback('#pre_render', Array, Array)\n#11 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#12 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(710): Drupal\\Core\\Render\\Renderer->render(Array)\n#13 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(577): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->renderFields(Array)\n#14 /var/www/html/web/core/modules/views/src/Plugin/views/style/StylePluginBase.php(468): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->renderGrouping(Array, Array, true)\n#15 /var/www/html/web/core/modules/views/src/Plugin/views/display/DisplayPluginBase.php(2170): Drupal\\views\\Plugin\\views\\style\\StylePluginBase->render(Array)\n#16 /var/www/html/web/core/modules/views/src/ViewExecutable.php(1533): Drupal\\views\\Plugin\\views\\display\\DisplayPluginBase->render()\n#17 /var/www/html/web/core/modules/views/src/Plugin/views/display/Page.php(183): Drupal\\views\\ViewExecutable->render()\n#18 /var/www/html/web/core/modules/views/src/ViewExecutable.php(1630): Drupal\\views\\Plugin\\views\\display\\Page->execute()\n#19 /var/www/html/web/core/modules/views/src/Element/View.php(77): Drupal\\views\\ViewExecutable->executeDisplay('page_1', Array)\n#20 [internal function]: Drupal\\views\\Element\\View::preRenderViewElement(Array)\n#21 /var/www/html/web/core/lib/Drupal/Core/Security/DoTrustedCallbackTrait.php(100): call_user_func_array(Array, Array)\n#22 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(781): Drupal\\Core\\Render\\Renderer->doTrustedCallback(Array, Array, 'Render #pre_ren...', 'silenced_deprec...', 'Drupal\\\\Core\\\\Ren...')\n#23 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(372): Drupal\\Core\\Render\\Renderer->doCallback('#pre_render', Array, Array)\n#24 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\\Core\\Render\\Renderer->doRender(Array, false)\n#25 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\\Core\\Render\\Renderer->render(Array, false)\n#26 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->Drupal\\Core\\Render\\MainContent\\{closure}()\n#27 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\\Core\\Render\\Renderer->executeInRenderContext(Object(Drupal\\Core\\Render\\RenderContext), Object(Closure))\n#28 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->prepare(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#29 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\\Core\\Render\\MainContent\\HtmlRenderer->renderResponse(Array, Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Routing\\CurrentRouteMatch))\n#30 [internal function]: Drupal\\Core\\EventSubscriber\\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#31 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#32 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent))\n#33 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#34 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#35 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\\Core\\StackMiddleware\\Session->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#36 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\\Core\\StackMiddleware\\KernelPreHandle->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#37 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\\page_cache\\StackMiddleware\\PageCache->pass(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#38 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\\page_cache\\StackMiddleware\\PageCache->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#39 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\\Core\\StackMiddleware\\ReverseProxyMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#40 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\\Core\\StackMiddleware\\NegotiationMiddleware->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#41 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(708): Stack\\StackedHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#42 /var/www/html/web/index.php(23): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#43 {main}
[Mon Sep 11 13:16:53.081299 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.3. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:32:50.689742 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:32:50.690106 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:33:59.503667 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.27.0.3. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:34:24.724455 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:34:24.724934 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:35:17.757122 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.0.3. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:35:27.401793 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:35:27.402298 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:36:37.852184 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.31.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:36:53.674242 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:36:53.674739 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:38:13.833823 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:38:23.586208 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:38:23.587734 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:39:59.428564 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.16.2. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:46:39.126363 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:46:39.126829 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:47:40.320819 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:49:24.489229 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:49:24.489885 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:50:32.694775 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:54:39.468743 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:54:39.469376 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:56:08.681259 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:56:20.766030 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:56:20.766549 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:57:20.555058 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:57:44.373924 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:57:44.374494 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:58:38.094536 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.22.0.3. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 13:58:49.964067 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 13:58:49.964951 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 13:59:57.880711 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.23.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:00:18.523134 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:00:18.523544 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:00:55.056241 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:01:42.852676 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:01:42.853066 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:02:29.313555 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:03:11.276378 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:03:11.277132 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:03:48.983342 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:04:18.238893 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:04:18.239321 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:04:59.542704 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.27.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:05:10.452011 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:05:10.452464 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:06:09.570447 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.28.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:07:49.653088 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:07:49.653527 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:08:12.095691 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.29.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:08:26.386969 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:08:26.387546 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:09:00.636464 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.30.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:09:22.603062 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:09:22.603573 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:10:29.631986 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.31.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:10:50.086890 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:10:50.087340 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:11:33.834940 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.0.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:11:58.018999 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:11:58.019849 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Mon Sep 11 14:12:44.852079 2023] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00112: Warning: DocumentRoot [/var/www/html/dameuntoke/web] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 192.168.16.4. Set the 'ServerName' directive globally to suppress this message
[Mon Sep 11 14:13:10.340950 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) PHP/7.3.33 configured -- resuming normal operations
[Mon Sep 11 14:13:10.341377 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
